'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating product descriptions using AI.
 *
 * It includes:
 * - generateProductDescription: An async function to generate product descriptions.
 * - GenerateProductDescriptionInput: The input type for the generateProductDescription function.
 * - GenerateProductDescriptionOutput: The output type for the generateProductDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProductDescriptionInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productCategory: z.string().describe('The category of the product.'),
  keyFeatures: z.string().describe('Key features of the product.'),
  targetAudience: z.string().describe('The target audience for the product.'),
  additionalDetails: z.string().optional().describe('Any additional details about the product.'),
});
export type GenerateProductDescriptionInput = z.infer<typeof GenerateProductDescriptionInputSchema>;

const GenerateProductDescriptionOutputSchema = z.object({
  productDescription: z.string().describe('A compelling product description generated by AI.'),
  suggestedTitle: z.string().describe('A suggested title for the product.'),
  suggestedKeywords: z.string().describe('Suggested keywords for SEO optimization.'),
});
export type GenerateProductDescriptionOutput = z.infer<typeof GenerateProductDescriptionOutputSchema>;

export async function generateProductDescription(
  input: GenerateProductDescriptionInput
): Promise<GenerateProductDescriptionOutput> {
  return generateProductDescriptionFlow(input);
}

const generateProductDescriptionPrompt = ai.definePrompt({
  name: 'generateProductDescriptionPrompt',
  input: {schema: GenerateProductDescriptionInputSchema},
  output: {schema: GenerateProductDescriptionOutputSchema},
  prompt: `You are an expert marketing copywriter specializing in e-commerce product descriptions.

  Based on the information provided, generate a compelling and informative product description, a suggested title, and some suggested keywords for SEO.

  Product Name: {{{productName}}}
  Product Category: {{{productCategory}}}
  Key Features: {{{keyFeatures}}}
  Target Audience: {{{targetAudience}}}
  Additional Details: {{{additionalDetails}}}

  Make sure that the product description is engaging, highlights the key benefits, and appeals to the target audience.
  The keywords should be relevant and optimized for search engines.
  The suggested title should be catchy and accurately reflect the product.
  `,
});

const generateProductDescriptionFlow = ai.defineFlow(
  {
    name: 'generateProductDescriptionFlow',
    inputSchema: GenerateProductDescriptionInputSchema,
    outputSchema: GenerateProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await generateProductDescriptionPrompt(input);
    return output!;
  }
);
