// This file is automatically generated. Do not modify it manually.
// To connect to a different Firebase project, restart the app and follow the prompts.
//
// HOW-TO:
// 1. Go to your Firebase project settings in the Firebase Console.
// 2. Under the "General" tab, find your web app in the "Your apps" section.
// 3. Look for "SDK setup and configuration" and select the "Config" option.
// 4. Copy the `firebaseConfig` object and paste it below, replacing the placeholder values.

export const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID"
};
