// This file is automatically generated. Do not modify it manually.
// To connect to a different Firebase project, restart the app and follow the prompts.
//
// HOW-TO:
// 1. Go to your Firebase project settings in the Firebase Console.
// 2. Under the "General" tab, find your web app in the "Your apps" section.
// 3. Look for "SDK setup and configuration" and select the "Config" option.
// 4. Copy the `firebaseConfig` object and paste it below, replacing the placeholder values.

export const firebaseConfig = {
  apiKey: "AIzaSyDa3JmR3JkDONdBZWIJrPqEy-oBIxFev7E",
  authDomain: "studio-8960281827-bdd3e.firebaseapp.com",
  projectId: "studio-8960281827-bdd3e",
  storageBucket: "studio-8960281827-bdd3e.appspot.com",
  messagingSenderId: "115609832823",
  appId: "1:115609832823:web:49c5a820af8900a5876572"
};
